# Generated by Django 5.2.3 on 2025-06-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_codigo_barras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precion_venta',
            new_name='precio_venta',
        ),
    ]
